# Generated by Django 3.0.8 on 2020-07-29 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image of food')),
                ('food_name', models.CharField(max_length=30, verbose_name='Name of the dish')),
                ('discription', models.TextField(verbose_name='Food discription')),
                ('price', models.IntegerField(verbose_name='Food price $')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Food',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=30, verbose_name="Author's name")),
                ('author_rate', models.IntegerField(verbose_name="Author's rate")),
                ('ratings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles2.Food')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
            },
        ),
    ]
